title: "Amelie Farren"
description: "Official Website"
baseurl: "" # Leave blank for GitHub Pages root
url: "https://ameliefarrenspiderlacewebsite.github.io" # Replace if using custom domain

plugins:
  - jekyll-feed
