title: "Amelie Farren"
description: "Official Website"
baseurl: "/ameliefarren.com"
url: "https://ameliefarrenspiderlacewebsite.github.io" # Replace if using custom domain

plugins:
  - jekyll-feed

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock